### ISSUE TITLE
tparty and drawdistance incomingchunk error

### ISSUE THREAD

**Issue by eslim** [z16/Lua#42]
every time these addons are loaded and some1 in linkshell says something, it'll error saying:

.. encountered a fatal error and must be terminated. Error: Access violation in IncomingChunk method.

must b due to the new ui and the way se now pushes linkshell messages etc..

/gives spirtuals

**Comment by z16** [comment]
These two plugins (along with [these](https://gist.github.com/z16/f73d0912e5c5ed02c58b)) are deprecated and no longer supported. Replacements for them are mentioned in the link.
