### ISSUE TITLE
Distance Add-On Not Visible

### ISSUE THREAD

**Issue by Vafruvant** [z16/Lua#43]
After switching to the Add-on version of Distance, it no longer loads on my screen. When the default settings didn't display it, I crossed it back to my old position, verified color settings, etc; still not appearing on the screen. It used to show up right underneath the word Help in the top bar of the UI. Any help would be very much appreciated. Thank you.

**Comment by z16** [comment]
Can you post the contents of your settings file?

**Comment by z16** [comment]
Also, what's your UI scale at?

**Comment by Vafruvant** [comment]
Nevermind, I was used to it always showing 0.0, I didn't realize you had to target something first *then* it appears. My apologies.
