### ISSUE TITLE
lua runtime error GearSwap/GearSwap.lua:382, lua runtime error GearSwap/GearSwap.lua:364

### ISSUE THREAD

**Issue by thecuriousorange** [z16/Lua#45]
"lua runtime error GearSwap/GearSwap.lua:364: attempt to index field '?' (returned a nil value)" occurs when I disengage.

"lua runtime error GearSwap/GearSwap.lua:382: attempt to index field '?' (returned a nil value)" occurs when I open /bank2 aka mog safe 2.

**Comment by thecuriousorange** [comment]
382 also pops up when I talk to a waypoint, it might pop up when I start to interact with an npc of any kind...

**Comment by thecuriousorange** [comment]
just popped up after running in north sandy as well, maybe because that's when my items load?

**Comment by z16** [comment]
You may wanna reopen this issue on Byrth's issue tracker or Windower's Lua issue tracker. This issue tracker is for my personal addons, and while I don't mind it, you're likely not getting much help from this, as I'm sure no one who can fix GearSwap is even seeing this.
